ln -s bash_aliases ~/.bash_aliases
ln -s bash_env     ~/.bash_env
ln -s bash_profile ~/.bash_profile
ln -s inputrc      ~/.inputrc
ln -s screenrc     ~/.screenrc
ln -s vim          ~/.vim
ln -s vimrc        ~/.vimrc
ln -s zsh_env      ~/.zsh_env
ln -s zshrc        ~/.zshrc
